ALTER TABLE employee_tickets
    ADD COLUMN IF NOT EXISTS hold_started_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS hold_reason TEXT NULL,
    ADD COLUMN IF NOT EXISTS hold_by INT NULL,
    ADD COLUMN IF NOT EXISTS sla_hold_seconds INT UNSIGNED NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sla_hold_seconds_at_high INT UNSIGNED NOT NULL DEFAULT 0;
